name: Add new issues to Project (Todo)

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project with status Todo
        uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/users/julienles879/projects/PVT_kwHOCKuDWM4BFmcx
          github-token: ${{ secrets.GITHUB_TOKEN }}
          item-id: ${{ github.event.issue.node_id }}
          field-Status: "Todo"
