name: Move Issue to In Progress (on branch creation)

on:
  create:
    branches:
      - "feature/**"

jobs:
  move-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Extract issue number
        id: extract
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          ISSUE_NUMBER=$(echo "$BRANCH_NAME" | grep -oE '#[0-9]+' | tr -d '#')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Get issue node_id
        if: env.ISSUE_NUMBER != ''
        run: |
          NODE_ID=$(gh api graphql -f query='
            query($o:String!,$r:String!,$n:Int!){
              repository(owner:$o,name:$r){issue(number:$n){id}}
            }' -F o="julienles879" -F r="uvents" -F n="$ISSUE_NUMBER" --jq '.data.repository.issue.id')
          echo "NODE_ID=$NODE_ID" >> $GITHUB_ENV

      - name: Move issue to In Progress
        if: env.NODE_ID != ''
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/julienles879/projects/1
          github-token: ${{ secrets.PROJECT_TOKEN }}
          item-id: ${{ env.NODE_ID }}
          field-Status: "In Progress"
