name: Move Issue to In Review (on PR open)

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Extract issue number from PR body
        id: extract
        run: |
          ISSUE_NUMBER=$(echo "${{ github.event.pull_request.body }}" | grep -oE '#[0-9]+' | tr -d '#')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_ENV

      - name: Get issue node_id
        if: env.ISSUE_NUMBER != ''
        run: |
          NODE_ID=$(gh api graphql -f query='
            query($o:String!,$r:String!,$n:Int!){
              repository(owner:$o,name:$r){issue(number:$n){id}}
            }' -F o="julienles879" -F r="uvents" -F n="$ISSUE_NUMBER" --jq '.data.repository.issue.id')
          echo "NODE_ID=$NODE_ID" >> $GITHUB_ENV

      - name: Move issue to In review
        if: env.NODE_ID != ''
        uses: actions/add-to-project@v0.4.0
        with:
            project-url: https://github.com/users/julienles879/projects/PVT_kwHOCKuDWM4BFmcx
          github-token: ${{ secrets.GITHUB_TOKEN }}
          item-id: ${{ env.NODE_ID }}
          field-Status: "In review"
